// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cortex/ent/predicate"
	"cortex/ent/tenant"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *TenantUpdate) SetSlug(v string) *TenantUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableSlug(v *string) *TenantUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdate) SetDomain(v string) *TenantUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableDomain(v *string) *TenantUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdate) ClearDomain() *TenantUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdate) SetStatus(v tenant.Status) *TenantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableStatus(v *tenant.Status) *TenantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *TenantUpdate) SetPlan(v tenant.Plan) *TenantUpdate {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *TenantUpdate) SetNillablePlan(v *tenant.Plan) *TenantUpdate {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *TenantUpdate) SetSettings(v map[string]interface{}) *TenantUpdate {
	_u.mutation.SetSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *TenantUpdate) ClearSettings() *TenantUpdate {
	_u.mutation.ClearSettings()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *TenantUpdate) SetMeta(v map[string]interface{}) *TenantUpdate {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *TenantUpdate) ClearMeta() *TenantUpdate {
	_u.mutation.ClearMeta()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdate) SetUpdatedAt(v time.Time) *TenantUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := tenant.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Tenant.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Domain(); ok {
		if err := tenant.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Tenant.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Tenant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Plan(); ok {
		if err := tenant.PlanValidator(v); err != nil {
			return &ValidationError{Name: "plan", err: fmt.Errorf(`ent: validator failed for field "Tenant.plan": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(tenant.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(tenant.FieldPlan, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(tenant.FieldSettings, field.TypeJSON, value)
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(tenant.FieldSettings, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(tenant.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(tenant.FieldMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *TenantUpdateOne) SetSlug(v string) *TenantUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableSlug(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *TenantUpdateOne) SetDomain(v string) *TenantUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableDomain(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *TenantUpdateOne) ClearDomain() *TenantUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetStatus sets the "status" field.
func (_u *TenantUpdateOne) SetStatus(v tenant.Status) *TenantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableStatus(v *tenant.Status) *TenantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlan sets the "plan" field.
func (_u *TenantUpdateOne) SetPlan(v tenant.Plan) *TenantUpdateOne {
	_u.mutation.SetPlan(v)
	return _u
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillablePlan(v *tenant.Plan) *TenantUpdateOne {
	if v != nil {
		_u.SetPlan(*v)
	}
	return _u
}

// SetSettings sets the "settings" field.
func (_u *TenantUpdateOne) SetSettings(v map[string]interface{}) *TenantUpdateOne {
	_u.mutation.SetSettings(v)
	return _u
}

// ClearSettings clears the value of the "settings" field.
func (_u *TenantUpdateOne) ClearSettings() *TenantUpdateOne {
	_u.mutation.ClearSettings()
	return _u
}

// SetMeta sets the "meta" field.
func (_u *TenantUpdateOne) SetMeta(v map[string]interface{}) *TenantUpdateOne {
	_u.mutation.SetMeta(v)
	return _u
}

// ClearMeta clears the value of the "meta" field.
func (_u *TenantUpdateOne) ClearMeta() *TenantUpdateOne {
	_u.mutation.ClearMeta()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantUpdateOne) SetUpdatedAt(v time.Time) *TenantUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tenant.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := tenant.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Tenant.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Domain(); ok {
		if err := tenant.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Tenant.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := tenant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Tenant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Plan(); ok {
		if err := tenant.PlanValidator(v); err != nil {
			return &ValidationError{Name: "plan", err: fmt.Errorf(`ent: validator failed for field "Tenant.plan": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(tenant.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(tenant.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(tenant.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(tenant.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Plan(); ok {
		_spec.SetField(tenant.FieldPlan, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Settings(); ok {
		_spec.SetField(tenant.FieldSettings, field.TypeJSON, value)
	}
	if _u.mutation.SettingsCleared() {
		_spec.ClearField(tenant.FieldSettings, field.TypeJSON)
	}
	if value, ok := _u.mutation.Meta(); ok {
		_spec.SetField(tenant.FieldMeta, field.TypeJSON, value)
	}
	if _u.mutation.MetaCleared() {
		_spec.ClearField(tenant.FieldMeta, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenant.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
